# Generated by Django 4.2.26 on 2025-11-27 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อรายหัก')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัส')),
                ('is_tax', models.BooleanField(default=False, verbose_name='เป็นภาษีไหม')),
                ('is_ssf', models.BooleanField(default=False, verbose_name='เป็นประกันสังคมไหม')),
            ],
        ),
        migrations.CreateModel(
            name='EarningType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อรายรับ')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัส')),
                ('is_taxable', models.BooleanField(default=True, verbose_name='นำไปคำนวณภาษีไหม')),
                ('is_ssf', models.BooleanField(default=True, verbose_name='นำไปคำนวณประกันสังคมไหม')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสพนักงาน')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มงาน')),
                ('status', models.CharField(choices=[('active', 'ทำงานอยู่'), ('inactive', 'ออกแล้ว')], default='active', max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ฐานเงินเดือน / เดือน')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ธนาคาร')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขบัญชี')),
                ('citizen_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขบัตรประชาชน')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False, verbose_name='ปิดรอบแล้วหรือไม่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายรับรวม')),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รายหักรวม')),
                ('net_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รับสุทธิ')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='app_hr.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='app_hr.payrollperiod')),
            ],
            options={
                'unique_together': {('employee', 'period')},
            },
        ),
        migrations.CreateModel(
            name='PayslipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('earning', 'รายรับ'), ('deduction', 'รายหัก')], max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อรายการ')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวนเงิน')),
                ('deduction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_hr.deductiontype')),
                ('earning_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_hr.earningtype')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_hr.payslip')),
            ],
        ),
    ]
