# Generated by Django 4.2.26 on 2025-11-27 07:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0002_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='เวลาเริ่มงานปกติ')),
                ('late_after_minutes', models.PositiveIntegerField(default=15, verbose_name='มาสายเกิน (นาที)')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_public_holiday', models.BooleanField(default=True, verbose_name='เป็นวันหยุดนักขัตฤกษ์')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('max_days_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='จำนวนวันต่อปีที่ลาได้')),
                ('is_paid', models.BooleanField(default=True, verbose_name='นับเป็นวันลาพร้อมเงินเดือน')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติ'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='app_hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_hr.leavetype')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'มาทำงาน'), ('late', 'มาสาย'), ('absent', 'ขาด'), ('leave', 'ลา'), ('holiday', 'วันหยุด')], default='present', max_length=20)),
                ('source', models.CharField(choices=[('csv', 'นำเข้าจาก CSV'), ('manual', 'กรอกด้วยมือ')], default='manual', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='app_hr.employee')),
            ],
            options={
                'ordering': ['-work_date', 'employee__code'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
