# Generated by Django 4.2.26 on 2025-11-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_hr', '0004_employee_address_employee_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_married', models.BooleanField(default=False, verbose_name='สมรส')),
                ('spouse_has_income', models.BooleanField(default=False, verbose_name='คู่สมรสมีรายได้')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='จำนวนบุตรที่ใช้สิทธิ์')),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='เบี้ยประกันชีวิต/สุขภาพ (ต่อปี)')),
                ('provident_fund', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='กองทุนสำรองเลี้ยงชีพ/กองทุนรวม (ต่อปี)')),
                ('home_loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ดอกเบี้ยกู้ซื้อบ้าน (ต่อปี)')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าลดหย่อนอื่น ๆ (ต่อปี)')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='app_hr.employee', verbose_name='พนักงาน')),
            ],
        ),
    ]
